"use client";

import { forwardRef } from "react";
import { formatDateShort, formatMoney } from "@/lib/format";
import type { PersonHistoryItem } from "@/types";

interface Props {
  messName: string;
  personName: string;
  periodLabel: string;
  meals: number;
  amount: number;
  currency: string;
  items: PersonHistoryItem[];
}

/** Off-screen styled card captured as an image for WhatsApp sharing. */
export const ShareCard = forwardRef<HTMLDivElement, Props>(function ShareCard(
  { messName, personName, periodLabel, meals, amount, currency, items },
  ref,
) {
  const dates = items.map((i) => formatDateShort(i.date));

  return (
    <div className="pointer-events-none fixed -left-[9999px] top-0">
      <div
        ref={ref}
        style={{ width: 380, fontFamily: "var(--font-sans), system-ui, sans-serif" }}
        className="bg-neutral-950 p-6 text-neutral-50"
      >
        <p className="text-xs uppercase tracking-widest text-neutral-400">{messName}</p>
        <h2 className="mt-3 text-2xl font-semibold">{personName}</h2>
        <p className="text-sm text-neutral-400">{periodLabel}</p>

        <div className="my-5 flex items-end justify-between border-y border-neutral-800 py-4">
          <div>
            <p className="text-xs text-neutral-400">Meals</p>
            <p className="text-xl font-semibold">{meals}</p>
          </div>
          <div className="text-right">
            <p className="text-xs text-neutral-400">Amount due</p>
            <p className="text-3xl font-bold">{formatMoney(amount, currency)}</p>
          </div>
        </div>

        {dates.length > 0 && (
          <div>
            <p className="text-xs text-neutral-400">Dates</p>
            <p className="mt-1 text-sm leading-relaxed text-neutral-200">{dates.join(" · ")}</p>
          </div>
        )}

        <p className="mt-5 text-[10px] text-neutral-500">Generated by Messy</p>
      </div>
    </div>
  );
});
